<?php

use Illuminate\Database\Seeder;

class visitor extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('visitors')->insert([
            ['country' => "Egypt",'users' => 0],
            ['country'=>"Bhutan",'users' =>0],
            ['country'=>"Democratic Republic of the Congo",'users' =>0],
            ['country'=>"Liechtenstein",'users' =>0],
            ['country'=>"Maldives",'users' =>0],
            ['country'=>"Sudan",'users' =>0],
            ['country'=>"Zimbabwe",'users' =>0],
            ['country'=>"Mauritania",'users' =>0],
            ['country'=>"Mozambique",'users' =>0],
            ['country'=>"Nigeria",'users' =>0],
            ['country'=>"Swaziland",'users' =>0],
            ['country'=>"Tanzania",'users' =>0],
            ['country'=>"Iraq",'users' =>0],
            ['country'=>"Guyana",'users' =>0],
            ['country'=>"Namibia",'users' =>0],
            ['country'=>"Senegal",'users' =>0],
            ['country'=>"Turkmenistan",'users' =>0],
            ['country'=>"Afghanistan",'users' =>0],
            ['country'=>"Andorra",'users' =>0],
            ['country'=>"Fiji",'users' =>0],
            ['country'=>"Gabon",'users' =>0],
            ['country'=>"Uzbekistan",'users' =>0],
            ['country'=>"Cameroon",'users' =>0],
            ['country'=>"Cuba",'users' =>0],
            ['country'=>"Faroe Islands",'users' =>0],
            ['country'=>"El Salvador",'users' =>0],
            ['country'=>"Caribbean",'users' =>0],
            ['country'=>"Ethiopia",'users' =>0],
            ['country'=>"Mongolia",'users' =>0],
            ['country'=>"Puerto Rico",'users' =>0],
            ['country'=>"Samoa",'users' =>0],
            ['country'=>"Myanmar",'users' =>0],
            ['country'=>"Nicaragua",'users' =>0],
            ['country'=>"Seychelles",'users' =>0],
            ['country'=>"Tajikistan",'users' =>0],
            ['country'=>"Dominican Republic",'users' =>0],
            ['country'=>"Guinea",'users' =>0],
            ['country'=>"Barbados",'users' =>0],
            ['country'=>"CI",'users' =>0],
            ['country'=>"Laos",'users' =>0],
            ['country'=>"Libya",'users' =>0],
            ['country'=>"Panama",'users' =>0],
            ['country'=>"Bahrain",'users' =>0],
            ['country'=>"Benin",'users' =>0],
            ['country'=>"Ghana",'users' =>0],
            ['country'=>"Haiti",'users' =>0],
            ['country'=>"Montenegro",'users' =>0],
            ['country'=>"Somalia",'users' =>0],
            ['country'=>"Syria",'users' =>0],
            ['country'=>"Ecuador",'users' =>0],
            ['country'=>"Honduras",'users' =>0],
            ['country'=>"Madagascar",'users' =>0],
            ['country'=>"Papua New Guinea",'users' =>0],
            ['country'=>"Tunisia",'users' =>0],
            ['country'=>"Angola",'users' =>0],
            ['country'=>"Botswana",'users' =>0],
            ['country'=>"Cyprus",'users' =>0],
            ['country'=>"Algeria",'users' =>0],
            ['country'=>"Bahamas",'users' =>0],
            ['country'=>"New Caledonia",'users' =>0],
            ['country'=>"Uganda",'users' =>0],
            ['country'=>"Yemen",'users' =>0],
            ['country'=>"Zambia",'users' =>0],
            ['country'=>"Antarctica",'users' =>0],
            ['country'=>"Paraguay",'users' =>0],
            ['country'=>"Jamaica",'users' =>0],
            ['country'=>"Palestine",'users' =>0],
            ['country'=>"Bolivia",'users' =>0],
            ['country'=>"Bosnia and Herzegovina",'users' =>0],
            ['country'=>"Vietnam",'users' =>0],
            ['country'=>"Kenya",'users' =>0],
            ['country'=>"Luxembourg",'users' =>0],
            ['country'=>"Niger",'users' =>0],
            ['country'=>"Kuwait",'users' =>0],
            ['country'=>"Hawaii",'users' =>0],
            ['country'=>"Scotland",'users' =>0],
            ['country'=>"Cambodia",'users' =>0],
            ['country'=>"Uruguay",'users' =>0],
            ['country'=>"Kyrgyzstan",'users' =>0],
            ['country'=>"Saudi Arabia",'users' =>0],
            ['country'=>"Indonesia",'users' =>0],
            ['country'=>"Azerbaijan",'users' =>0],
            ['country'=>"United Arab Emirates",'users' =>0],
            ['country'=>"Mauritius",'users' =>0],
            ['country'=>"Morocco",'users' =>0],
            ['country'=>"Albania",'users' =>0],
            ['country'=>"South Korea",'users' =>0],
            ['country'=>"Kazakhstan",'users' =>0],
            ['country'=>"Macedonia",'users' =>0],
            ['country'=>"Venezuela",'users' =>0],
            ['country'=>"Taiwan",'users' =>0],
            ['country'=>"Qatar",'users' =>0],
            ['country'=>"Jordan",'users' =>0],
            ['country'=>"Iceland",'users' =>0],
            ['country'=>"Guatemala",'users' =>0],
            ['country'=>"Costa Rica",'users' =>0],
            ['country'=>"Hong Kong",'users' =>0],
            ['country'=>"San Marino",'users' =>0],
            ['country'=>"Colombia",'users' =>0],
            ['country'=>"Moldova",'users' =>0],
            ['country'=>"Armenia",'users' =>0],
            ['country'=>"Malta",'users' =>0],
            ['country'=>"Nepal",'users' =>0],
            ['country'=>"Lebanon",'users' =>0],
            ['country'=>"Malaysia",'users' =>0],
            ['country'=>"Serbia",'users' =>0],
            ['country'=>"Peru",'users' =>0],
            ['country'=>"Trinidad and Tobago",'users' =>0],
            ['country'=>"Lithuania",'users' =>0],
            ['country'=>"Estonia",'users' =>0],
            ['country'=>"Georgia",'users' =>0],
            ['country'=>"Iran",'users' =>0],
            ['country'=>"Chile",'users' =>0],
            ['country'=>"Latvia",'users' =>0],
            ['country'=>"Thailand",'users' =>0],
            ['country'=>"Egypt",'users' =>0],
            ['country'=>"Slovenia",'users' =>0],
            ['country'=>"Mexico",'users' =>0],
            ['country'=>"Belarus",'users' =>0],
            ['country'=>"Slovakia",'users' =>0],
            ['country'=>"Sri Lanka",'users' =>0],
            ['country'=>"Croatia",'users' =>0],
            ['country'=>"Philippines",'users' =>0],
            ['country'=>"Bangladesh",'users' =>0],
            ['country'=>"Turkey",'users' =>0],
            ['country'=>"Romania",'users' =>0],
            ['country'=>"Italy",'users' =>0],
            ['country'=>"South Africa",'users' =>0],
            ['country'=>"Hungary",'users' =>0],
            ['country'=>"Pakistan",'users' =>0],
            ['country'=>"Portugal",'users' =>0],
            ['country'=>"Ukraine",'users' =>0],
            ['country'=>"Greece",'users' =>0],
            ['country'=>"Oman",'users' =>0],
            ['country'=>"Argentina",'users' =>0],
            ['country'=>"Singapore",'users' =>0],
            ['country'=>"Bulgaria",'users' =>0],
            ['country'=>"Japan",'users' =>0],
            ['country'=>"Czech Republic ",'users' =>0],
            ['country'=>"Ireland",'users' =>0],
            ['country'=>"China",'users' =>0],
            ['country'=>"Finland",'users' =>0],
            ['country'=>"Brazil",'users' =>0],
            ['country'=>"Norway",'users' =>0],
            ['country'=>"Austria",'users' =>0],
            ['country'=>"Denmark",'users' =>0],
            ['country'=>"Belgium",'users' =>0],
            ['country'=>"New Zealand",'users' =>0],
            ['country'=>"Spain",'users' =>0],
            ['country'=>"Switzerland",'users' =>0],
            ['country'=>"Russia",'users' =>0],
            ['country'=>"Poland",'users' =>0],
            ['country'=>"Israel",'users' =>0],
            ['country'=>"Sweden",'users' =>0],
            ['country'=>"Netherlands",'users' =>0],
            ['country'=>"France",'users' =>0],
            ['country'=>"Australia",'users' =>0],
            ['country'=>"Canada",'users' =>0],
            ['country'=>"India",'users' =>0],
            ['country'=>"Germany",'users' =>0],
            ['country'=>"United Kingdom",'users' =>0],
            ['country'=>"United States",'users' =>0]]);
    }
}
